"use client"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import { ToastContainer, toast } from 'react-toastify';
  import 'react-toastify/dist/ReactToastify.css';
  import { FormProvider } from './clientregister/FormContext/page';
import {store,persistor} from './redux/store'
import { Provider } from 'react-redux';
import { PersistGate } from 'redux-persist/integration/react';
import { FormFillProvider } from './freelenceregister/FormContext';
const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
<html lang="en">
<Provider store={store}>
  
  <FormProvider>
    <FormFillProvider>
  <body className={inter.className}>
    <ToastContainer></ToastContainer>
    {children}
    </body>
    </FormFillProvider>
  </FormProvider>
 
  </Provider>
    </html>
  )
}
