import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import { FormProvider } from './clientregister/FormContext/page';
import { FormFillProvider } from './freelenceregister/FormContext';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
<html lang="en">
  <FormProvider>
  <FormFillProvider>
  <body className={inter.className}>
   {children}
    </body>
    </FormFillProvider>
  </FormProvider>
  
    </html>
  )
}
